name: Google Tests

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-2022
    strategy:
      matrix:
        config: [debug, release]
        target:
          - YakoEngineLibTester

    env:
      TEST_REPORT_PATH: ${{github.workspace}}/Build/Bin/${{matrix.target}}-report.xml

    steps:
      - name: Loading code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - name: Install CMake
        run: pip install cmake

      - name: Install Conan
        run: pip install conan

      - name: Install clang-format
        run: pip install clang-format

      - name: Verify installations
        run: |
          python --version
          cmake --version
          conan --version
          clang-format --version

      - name: Build ${{ matrix.config }}
        working-directory: Scripts/Windows
        shell: cmd
        run: |
          build-${{ matrix.config }}.bat

      - name: Setup Mesa3D (Software OpenGL)
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "https://github.com/pal1000/mesa-dist-win/releases/download/23.1.9/mesa3d-23.1.9-release-msvc.7z" -OutFile mesa3d.7z
          & "C:\Program Files\7-Zip\7z.exe" x mesa3d.7z -omesa

          $target = "${{github.workspace}}\Build\Bin\Runtime\${{matrix.config}}"
          Copy-Item -Force "mesa\x64\opengl32.dll" $target
          Copy-Item -Force "mesa\x64\libglapi.dll" $target
          Copy-Item -Force "mesa\x64\libgallium_wgl.dll" $target

          "GALLIUM_DRIVER=llvmpipe" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Run Tests
        run: ${{github.workspace}}/Build/Bin/Runtime/${{matrix.config}}/${{matrix.target}}.exe --gtest_output=xml:"${{env.TEST_REPORT_PATH}}"

      - name: Upload Test Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: TestResults-${{matrix.target}}
          path: ${{env.TEST_REPORT_PATH}}

      - name: Publish Tests Report
        uses: phoenix-actions/test-reporting@v10
        if: always()
        with:
          name: Test Results
          path: "**/*-report.xml"
          reporter: java-junit
          output-to: "step-summary"
          fail-on-error: "true"