name: Google Tests

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-2022
    strategy:
      matrix:
        config: [debug, release]
        target:
          - YakoEngineTester

    env:
      TEST_REPORT_PATH: ${{github.workspace}}/Build/Bin/${{matrix.target}}-report.xml

    steps:
      - name: Loading code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - name: Install CMake
        run: pip install cmake

      - name: Install Conan
        run: pip install conan

      - name: Install clang-format
        run: pip install clang-format

      - name: Verify installations
        run: |
          python --version
          cmake --version
          conan --version
          clang-format --version

      - name: Build ${{ matrix.config }}
        working-directory: Scripts/Windows
        shell: cmd
        run: |
          build-${{ matrix.config }}.bat

      - name: Run Tests
        run: ${{github.workspace}}/Build/Bin/Runtime/${{matrix.config}}/${{matrix.target}}.exe --gtest_output=xml:"${{env.TEST_REPORT_PATH}}"

      - name: Upload Test Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: TestResults-${{matrix.target}}
          path: ${{env.TEST_REPORT_PATH}}

      - name: Publish Tests Report
        uses: phoenix-actions/test-reporting@v10
        if: always()
        with:
          name: Test Results
          path: "**/*-report.xml"
          reporter: java-junit
          output-to: "step-summary"
          fail-on-error: "true"